### ISSUE TITLE
Historical data is improper for India from 24th May

### ISSUE THREAD

**Issue by AryaAJ** [COVID19-SARS-CoV-2/web-covid-api#10]
Hi friend,

I am developing a free app for covid19 and trying to integrate your APIs.

The historical data for india is messed up it seems. all values are null or zero.

Query : 

query {
country(name: "India"){
cases
  historical(reverse: true){
    cases
    todayRecovered
    todayCases
    todayDeaths
    date
  }
country
}
}

Response:

{
  "data": {
    "country": {
      "cases": 227273,
      "historical": [
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "6/4/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "6/3/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "6/2/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "6/1/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/31/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/30/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/29/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/28/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/27/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/26/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/25/20"
        },
        {
          "cases": 131426,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "5/24/20"
        },
        {
          "cases": 131424,
          "todayRecovered": 2576,
          "todayCases": 6667,
          "todayDeaths": 142,
          "date": "5/23/20"
        },
        {
          "cases": 124759,
          "todayRecovered": 3280,
          "todayCases": 6536,
          "todayDeaths": 142,
          "date": "5/22/20"
        },
        {
          "cases": 118223,
          "todayRecovered": 3131,
          "todayCases": 6023,
          "todayDeaths": 148,
          "date": "5/21/20"
        },
        {
          "cases": 112200,
          "todayRecovered": 3113,
          "todayCases": 5720,
          "todayDeaths": 134,
          "date": "5/20/20"
        },
        {
          "cases": 106480,
          "todayRecovered": 3032,
          "todayCases": 6154,
          "todayDeaths": 146,
          "date": "5/19/20"
        },
        {
          "cases": 100326,
          "todayRecovered": 2482,
          "todayCases": 4628,
          "todayDeaths": 131,
          "date": "5/18/20"
        },
        {
          "cases": 95698,
          "todayRecovered": 2538,
          "todayCases": 5049,
          "todayDeaths": 152,
          "date": "5/17/20"
        },
        {
          "cases": 90649,
          "todayRecovered": 4012,
          "todayCases": 4794,
          "todayDeaths": 120,
          "date": "5/16/20"
        },
        {
          "cases": 85855,
          "todayRecovered": 2234,
          "todayCases": 3808,
          "todayDeaths": 104,
          "date": "5/15/20"
        },
        {
          "cases": 82047,
          "todayRecovered": 1594,
          "todayCases": 3991,
          "todayDeaths": 97,
          "date": "5/14/20"
        },
        {
          "cases": 78056,
          "todayRecovered": 1963,
          "todayCases": 3726,
          "todayDeaths": 137,
          "date": "5/13/20"
        },
        {
          "cases": 74330,
          "todayRecovered": 1905,
          "todayCases": 3562,
          "todayDeaths": 120,
          "date": "5/12/20"
        },
        {
          "cases": 70768,
          "todayRecovered": 1579,
          "todayCases": 3592,
          "todayDeaths": 81,
          "date": "5/11/20"
        },
        {
          "cases": 67176,
          "todayRecovered": 1669,
          "todayCases": 4311,
          "todayDeaths": 112,
          "date": "5/10/20"
        },
        {
          "cases": 62865,
          "todayRecovered": 1414,
          "todayCases": 3175,
          "todayDeaths": 115,
          "date": "5/9/20"
        },
        {
          "cases": 59690,
          "todayRecovered": 1111,
          "todayCases": 3339,
          "todayDeaths": 97,
          "date": "5/8/20"
        },
        {
          "cases": 56351,
          "todayRecovered": 1475,
          "todayCases": 3344,
          "todayDeaths": 104,
          "date": "5/7/20"
        },
        {
          "cases": 53007,
          "todayRecovered": 1161,
          "todayCases": 3602,
          "todayDeaths": 91,
          "date": "5/6/20"
        },
        {
          "cases": 49405,
          "todayRecovered": 1295,
          "todayCases": 2971,
          "todayDeaths": 128,
          "date": "5/5/20"
        },
        {
          "cases": 46434,
          "todayRecovered": 1082,
          "todayCases": 3656,
          "todayDeaths": 103,
          "date": "5/4/20"
        },
        {
          "cases": 42778,
          "todayRecovered": 911,
          "todayCases": 2952,
          "todayDeaths": 140,
          "date": "5/3/20"
        },
        {
          "cases": 39826,
          "todayRecovered": 831,
          "todayCases": 2564,
          "todayDeaths": 92,
          "date": "5/2/20"
        },
        {
          "cases": 37262,
          "todayRecovered": 962,
          "todayCases": 2396,
          "todayDeaths": 77,
          "date": "5/1/20"
        },
        {
          "cases": 34866,
          "todayRecovered": 630,
          "todayCases": 1801,
          "todayDeaths": 75,
          "date": "4/30/20"
        },
        {
          "cases": 33065,
          "todayRecovered": 690,
          "todayCases": 1705,
          "todayDeaths": 71,
          "date": "4/29/20"
        },
        {
          "cases": 31360,
          "todayRecovered": 636,
          "todayCases": 1902,
          "todayDeaths": 69,
          "date": "4/28/20"
        },
        {
          "cases": 29458,
          "todayRecovered": 580,
          "todayCases": 1568,
          "todayDeaths": 58,
          "date": "4/27/20"
        },
        {
          "cases": 27890,
          "todayRecovered": 585,
          "todayCases": 1607,
          "todayDeaths": 56,
          "date": "4/26/20"
        },
        {
          "cases": 26283,
          "todayRecovered": 442,
          "todayCases": 1835,
          "todayDeaths": 44,
          "date": "4/25/20"
        },
        {
          "cases": 24448,
          "todayRecovered": 484,
          "todayCases": 1408,
          "todayDeaths": 59,
          "date": "4/24/20"
        },
        {
          "cases": 23040,
          "todayRecovered": 642,
          "todayCases": 1667,
          "todayDeaths": 40,
          "date": "4/23/20"
        },
        {
          "cases": 21373,
          "todayRecovered": 394,
          "todayCases": 1292,
          "todayDeaths": 36,
          "date": "4/22/20"
        },
        {
          "cases": 20081,
          "todayRecovered": 703,
          "todayCases": 1537,
          "todayDeaths": 53,
          "date": "4/21/20"
        },
        {
          "cases": 18544,
          "todayRecovered": 419,
          "todayCases": 1239,
          "todayDeaths": 33,
          "date": "4/20/20"
        },
        {
          "cases": 17305,
          "todayRecovered": 388,
          "todayCases": 1580,
          "todayDeaths": 38,
          "date": "4/19/20"
        },
        {
          "cases": 15725,
          "todayRecovered": 426,
          "todayCases": 1371,
          "todayDeaths": 35,
          "date": "4/18/20"
        },
        {
          "cases": 14354,
          "todayRecovered": 273,
          "todayCases": 922,
          "todayDeaths": 38,
          "date": "4/17/20"
        },
        {
          "cases": 13432,
          "todayRecovered": 258,
          "todayCases": 1061,
          "todayDeaths": 26,
          "date": "4/16/20"
        },
        {
          "cases": 12371,
          "todayRecovered": 144,
          "todayCases": 886,
          "todayDeaths": 27,
          "date": "4/15/20"
        },
        {
          "cases": 11485,
          "todayRecovered": 167,
          "todayCases": 1031,
          "todayDeaths": 37,
          "date": "4/14/20"
        },
        {
          "cases": 10454,
          "todayRecovered": 112,
          "todayCases": 1243,
          "todayDeaths": 27,
          "date": "4/13/20"
        },
        {
          "cases": 9211,
          "todayRecovered": 114,
          "todayCases": 758,
          "todayDeaths": 42,
          "date": "4/12/20"
        },
        {
          "cases": 8453,
          "todayRecovered": 186,
          "todayCases": 854,
          "todayDeaths": 41,
          "date": "4/11/20"
        },
        {
          "cases": 7599,
          "todayRecovered": 151,
          "todayCases": 871,
          "todayDeaths": 22,
          "date": "4/10/20"
        },
        {
          "cases": 6728,
          "todayRecovered": 70,
          "todayCases": 813,
          "todayDeaths": 46,
          "date": "4/9/20"
        },
        {
          "cases": 5915,
          "todayRecovered": 96,
          "todayCases": 565,
          "todayDeaths": 20,
          "date": "4/8/20"
        },
        {
          "cases": 5350,
          "todayRecovered": 75,
          "todayCases": 573,
          "todayDeaths": 27,
          "date": "4/7/20"
        },
        {
          "cases": 4777,
          "todayRecovered": 65,
          "todayCases": 484,
          "todayDeaths": 16,
          "date": "4/6/20"
        },
        {
          "cases": 4293,
          "todayRecovered": 43,
          "todayCases": 609,
          "todayDeaths": 22,
          "date": "4/5/20"
        },
        {
          "cases": 3684,
          "todayRecovered": 56,
          "todayCases": 579,
          "todayDeaths": 13,
          "date": "4/4/20"
        },
        {
          "cases": 3105,
          "todayRecovered": 39,
          "todayCases": 560,
          "todayDeaths": 14,
          "date": "4/3/20"
        },
        {
          "cases": 2545,
          "todayRecovered": 22,
          "todayCases": 486,
          "todayDeaths": 16,
          "date": "4/2/20"
        },
        {
          "cases": 2059,
          "todayRecovered": 19,
          "todayCases": 424,
          "todayDeaths": 6,
          "date": "4/1/20"
        },
        {
          "cases": 1635,
          "todayRecovered": 13,
          "todayCases": 309,
          "todayDeaths": 6,
          "date": "3/31/20"
        },
        {
          "cases": 1326,
          "todayRecovered": 35,
          "todayCases": 187,
          "todayDeaths": 14,
          "date": "3/30/20"
        },
        {
          "cases": 1139,
          "todayRecovered": 17,
          "todayCases": 120,
          "todayDeaths": 3,
          "date": "3/29/20"
        },
        {
          "cases": 1019,
          "todayRecovered": 10,
          "todayCases": 136,
          "todayDeaths": 5,
          "date": "3/28/20"
        },
        {
          "cases": 883,
          "todayRecovered": 25,
          "todayCases": 153,
          "todayDeaths": 3,
          "date": "3/27/20"
        },
        {
          "cases": 730,
          "todayRecovered": 7,
          "todayCases": 73,
          "todayDeaths": 5,
          "date": "3/26/20"
        },
        {
          "cases": 657,
          "todayRecovered": 3,
          "todayCases": 86,
          "todayDeaths": 1,
          "date": "3/25/20"
        },
        {
          "cases": 571,
          "todayRecovered": 15,
          "todayCases": 74,
          "todayDeaths": 1,
          "date": "3/24/20"
        },
        {
          "cases": 497,
          "todayRecovered": 2,
          "todayCases": 94,
          "todayDeaths": 2,
          "date": "3/23/20"
        },
        {
          "cases": 403,
          "todayRecovered": 0,
          "todayCases": 69,
          "todayDeaths": 3,
          "date": "3/22/20"
        },
        {
          "cases": 334,
          "todayRecovered": 0,
          "todayCases": 78,
          "todayDeaths": 0,
          "date": "3/21/20"
        },
        {
          "cases": 256,
          "todayRecovered": 3,
          "todayCases": 58,
          "todayDeaths": 0,
          "date": "3/20/20"
        },
        {
          "cases": 198,
          "todayRecovered": 5,
          "todayCases": 27,
          "todayDeaths": 1,
          "date": "3/19/20"
        },
        {
          "cases": 171,
          "todayRecovered": 0,
          "todayCases": 25,
          "todayDeaths": 0,
          "date": "3/18/20"
        },
        {
          "cases": 146,
          "todayRecovered": 1,
          "todayCases": 20,
          "todayDeaths": 1,
          "date": "3/17/20"
        },
        {
          "cases": 126,
          "todayRecovered": 1,
          "todayCases": 14,
          "todayDeaths": 0,
          "date": "3/16/20"
        },
        {
          "cases": 112,
          "todayRecovered": 3,
          "todayCases": 10,
          "todayDeaths": 0,
          "date": "3/15/20"
        },
        {
          "cases": 102,
          "todayRecovered": 0,
          "todayCases": 11,
          "todayDeaths": 1,
          "date": "3/14/20"
        },
        {
          "cases": 91,
          "todayRecovered": 6,
          "todayCases": 10,
          "todayDeaths": 0,
          "date": "3/13/20"
        },
        {
          "cases": 81,
          "todayRecovered": 0,
          "todayCases": 10,
          "todayDeaths": 1,
          "date": "3/12/20"
        },
        {
          "cases": 71,
          "todayRecovered": 0,
          "todayCases": 8,
          "todayDeaths": 0,
          "date": "3/11/20"
        },
        {
          "cases": 63,
          "todayRecovered": 1,
          "todayCases": 15,
          "todayDeaths": 0,
          "date": "3/10/20"
        },
        {
          "cases": 48,
          "todayRecovered": 0,
          "todayCases": 9,
          "todayDeaths": 0,
          "date": "3/9/20"
        },
        {
          "cases": 39,
          "todayRecovered": 0,
          "todayCases": 5,
          "todayDeaths": 0,
          "date": "3/8/20"
        },
        {
          "cases": 34,
          "todayRecovered": 0,
          "todayCases": 3,
          "todayDeaths": 0,
          "date": "3/7/20"
        },
        {
          "cases": 31,
          "todayRecovered": 0,
          "todayCases": 1,
          "todayDeaths": 0,
          "date": "3/6/20"
        },
        {
          "cases": 30,
          "todayRecovered": 0,
          "todayCases": 2,
          "todayDeaths": 0,
          "date": "3/5/20"
        },
        {
          "cases": 28,
          "todayRecovered": 0,
          "todayCases": 22,
          "todayDeaths": 0,
          "date": "3/4/20"
        },
        {
          "cases": 6,
          "todayRecovered": 0,
          "todayCases": 1,
          "todayDeaths": 0,
          "date": "3/3/20"
        },
        {
          "cases": 5,
          "todayRecovered": 0,
          "todayCases": 2,
          "todayDeaths": 0,
          "date": "3/2/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "3/1/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/29/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/28/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/27/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/26/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/25/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/24/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/23/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/22/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/21/20"
        },
        {
          "cases": 3,
          "todayRecovered": 1,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/20/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/19/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/18/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/17/20"
        },
        {
          "cases": 3,
          "todayRecovered": 1,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/16/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/15/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/14/20"
        },
        {
          "cases": 3,
          "todayRecovered": 1,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/13/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/12/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/11/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/10/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/9/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/8/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/7/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/6/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/5/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/4/20"
        },
        {
          "cases": 3,
          "todayRecovered": 0,
          "todayCases": 1,
          "todayDeaths": 0,
          "date": "2/3/20"
        },
        {
          "cases": 2,
          "todayRecovered": 0,
          "todayCases": 1,
          "todayDeaths": 0,
          "date": "2/2/20"
        },
        {
          "cases": 1,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "2/1/20"
        },
        {
          "cases": 1,
          "todayRecovered": 0,
          "todayCases": 0,
          "todayDeaths": 0,
          "date": "1/31/20"
        },
        {
          "cases": 1,
          "todayRecovered": 0,
          "todayCases": 1,
          "todayDeaths": 0,
          "date": "1/30/20"
        }
      ],
      "country": "India"
    }
  }
}

**Comment by VisahanA** [comment]
Hey Arya,
       There was a problem in our source data.The issue has been addressed and fixed.Enjoy using our API 😁

**Comment by AryaAJ** [comment]
Thank you so much brother.

Sent from Yahoo Mail on Android 
 
  On Sun, 7 Jun 2020 at 12:39 pm, Visahan.A<notifications@github.com> wrote:   


Hey Arya,
There was a problem in our source data.The issue has been addressed and fixed.Enjoy using our API 😁

**Comment by AryaAJ** [comment]
Working thanks for this!!
