### ISSUE TITLE
District Historical Data

### ISSUE THREAD

**Issue by rajesvariparasa** [COVID19-SARS-CoV-2/web-covid-api#2]
Would be extremely helpful if we can get queries for Historical District wise data. I think current queries allow only access to latest district data. Thank you!

**Comment by VisahanA** [comment]
Thanks for the suggestion. We will add historic for both state-wise and district-wise

**Comment by skavinvarnan** [comment]
Historical for district has been added. 

Open: https://covidstat.info/graphql

```graphql
# Get historical for all districts in all states
query {
  country(name: "India") {
    states {
      state
      districts {
        district
        historical {
          date
          cases
          deaths
          recovered
        }
      }
    }
  }
}

or

# Get historical for all districts in a particular state
query {
  state(countryName: "India", stateName: "Tamil Nadu") {
    state
    districts {
      district
      historical {
        date
        cases
        deaths
        recovered
      }
    }
  }
}
```

You can also get historic statewise here - https://github.com/COVID19-SARS-CoV-2/web-covid-api/blob/master/india_apis.md#6-get-historic-data-for-state
