### ISSUE TITLE
Looking for dry Cough sound from COVID 19 patients

### ISSUE THREAD

**Issue by darunk67** [COVID19-SARS-CoV-2/web-covid-api#3]
hi All,

I have an idea to classify the COVID 19 positive patients by using their dry cough sounds/breathing sounds. It can be done through the mobile app by using a microphone. Because while traveling from home to Labs/Hospital to test COVID 19 test, it may be possible to spread the virus to anyone or it may impact the person who doesn't have the COVID 19 positive also. So, it can easily be screening when they are at home itself. if the person wants the treatment, we can provide the treatment from home or will take them into the hospital. I am looking for dry cough and breath sounds from COVID 19 positive. 

Thanks,
Arun Kumar Durairaj,
darunk67@gmail.com.

**Comment by VisahanA** [comment]
Hey Arun Kumar Durairaj,
        Currently we are not providing any sample sets of data for dry-cough and breath sounds, if we find to get some data regarding these we will update the details.

Regards,
Visahan Ashok

**Comment by darunk67** [comment]
Thanks for your response.
