### ISSUE TITLE
URL for statewise historical data

### ISSUE THREAD

**Issue by srivastavakash** [COVID19-SARS-CoV-2/web-covid-api#4]
Cannot get the endpoint for historical data of all states

**Comment by skavinvarnan** [comment]
Try these

Go to: https://covidstat.info/graphql

#### 1. All States combined historical, can also be considered as historical for India
```graphql
query {
  country(name: "India") {
    historical {
      date
      cases
      deaths
      recovered
      todayCases
      todayRecovered
      todayDeaths
    }
  }
}
```

#### 2. Historical data for individual states
```graphql
query {
  country(name: "India") {
    states {
      state
      historical {
        date
        cases
        deaths
        recovered
        todayCases
        todayRecovered
        todayDeaths
      }
    }
  }
}
```

You can check out the detailed document here https://github.com/COVID19-SARS-CoV-2/web-covid-api/blob/master/india_apis.md#5-get-historic-data-for-india

**Comment by srivastavakash** [comment]
Can I get the data by making API request ?

**Comment by skavinvarnan** [comment]
Yes you can do it through a regular HTTP POST request. Check out these references
1. https://graphql.org/learn/serving-over-http/
2. https://www.apollographql.com/docs/apollo-server/v1/requests/
