### ISSUE TITLE
Historical data: Option for filtering by date

### ISSUE THREAD

**Issue by curioustechizen** [COVID19-SARS-CoV-2/web-covid-api#5]
Thanks for this API. I'm using it to fetch the details for India and I find it easier to use than the underlying Covid19 India API directly.

I'm a total newbie when it comes to GraphQL. I see that the historical data section of the API and in the playground I can see how to query historical data.

I would like to filter historical queries by date (for example, only fetch info for the last 2 weeks). I could not find a way to achieve this. Googling for it says it is not part of the GraphQL spec.

Any ideas on how to achieve this (other than querying everything and filtering client-side)?

**Comment by curioustechizen** [comment]
This specific use case can probably be solved using pagination, but I haven't figured out how to construct the query in the playground to get paginated results.

**Comment by skavinvarnan** [comment]
Thanks for your suggestion. I will modify the query to support pagination. 

Will create filter based on this guide https://graphql.org/learn/pagination/#pagination-and-edges

Will something like this help?
```graphql
query {
  country(name: "India") {
    country
    historical(first:10 offset:4) {
      date
      cases
    }
  }
}
```

**Comment by curioustechizen** [comment]
That would be great. Thanks! 

Does the paging spec support `last` as well? I assume that the results are sorted in ascending order of date (starting from Jan 30), so `last` is probably more helpful than `first`.

The page you linked to only mentions `first`, but I did see some examples of `last`. This one is for the GitHub GraphQL API:

```
    viewer {
      repositories(last: 50) {
        nodes {
          __typename
          id
          name
          viewerHasStarred
        }
      }
    }
```

Source: https://pub.dev/packages/graphql#query

**Comment by skavinvarnan** [comment]
Got it. I will add three fields
```
count: 10
skip: 30
reverse: true
```

With these three fields you will be able to customise to any extend

**Comment by skavinvarnan** [comment]
Historic filtering can be done on Country, State and District. 

Checkout this document: https://github.com/COVID19-SARS-CoV-2/web-covid-api/blob/master/india_apis.md#historical-filter
