### ISSUE TITLE
data null

### ISSUE THREAD

**Issue by rakeshkokkula** [COVID19-SARS-CoV-2/web-covid-api#6]
bro its showing data null for some queries and its not showing total all the datails 
![data 2](https://user-images.githubusercontent.com/50906633/82012750-5abfc700-9696-11ea-9994-3be8f884679a.PNG)

![data null](https://user-images.githubusercontent.com/50906633/82012493-bd649300-9695-11ea-82d7-3488074b0f00.PNG)

**Comment by skavinvarnan** [comment]
There is a problem in our source data. We are working on it. Will keep you updated

**Comment by rakeshkokkula** [comment]
> There is a problem in our source data. We are working on it. Will keep you updated

ok bro thank you for your quick response

**Comment by VisahanA** [comment]
The issue has been solved 😀. Sorry for the inconvenience 😔. Enjoy using our API 😁
